// <auto-generated />
using System;
using JwtUser.Repos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JwtUser.Migrations
{
    [DbContext(typeof(LearnDataContext))]
    [Migration("20250220054858_RefreshTokenTableChange")]
    partial class RefreshTokenTableChange
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);


            modelBuilder.Entity("JwtUser.Repos.Models.TblRefreshtoken", b =>
                {
                    b.Property<string>("Userid")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("userid");

                    b.Property<string>("Tokenid")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("tokenid");

                    b.Property<DateTime?>("Expiretime")
                        .HasColumnType("datetime")
                        .HasColumnName("expiretime");

                    b.Property<string>("Refreshtoken")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("refreshtoken");

                    b.Property<string>("TblUserUserId")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Userid", "Tokenid");

                    b.HasIndex("TblUserUserId");

                    b.ToTable("tbl_refreshtoken");
                });

            modelBuilder.Entity("JwtUser.Repos.Models.TblRefreshtoken", b =>
                {
                    b.HasOne("JwtUser.Repos.Models.TblUser", null)
                        .WithMany("RefreshTokens")
                        .HasForeignKey("TblUserUserId");
                });

            modelBuilder.Entity("JwtUser.Repos.Models.TblUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
